[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
